version: '3'

services:
  notebook:
    container_name: whatsUUUUP
    build:
      context: ./notebook
      dockerfile: Dockerfile.notebook
    privileged: true
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - $PWD/workspace:/workspace
    ports:
      - "8888:8888"
    networks:
      - network_1

networks:
    network_1: